SetExtraGun 
ShowFisherUi    
BingoGetDeductCount 
BingoGetAwardResult 
GetSelfName 
SetBingoAwardInfo   
ResultAwardInfo 
SetBigAwardInfo 
OpenTreasureChest   
Console 
OpenBattleSelect    
SetBattleSelectPage 
SetBattleSelectInfo 
ClientTalk  
IsUiHelpStatus  
ExportLadderByID    
ExportLadder    
NewTask_RemoveMapCoordinate 
NewTask_AddMapCoordinate    
NewTask_ShowTask    
NewTask_ChangeMouseTip  
NewTask_IsMaxNum    
NewTask_SetFinishedTask 
NewTask_DeleteIcon  
NewTask_AddIcon 
NewTask_AddNpcFindPath  
NewTask_DetailTextOut   
NewTask_TaskTextOut 
BanChannel  
Zoom    
ConstructFilter 
WorldFilter 
ChangeMiniMap   
TransferCmd 
CheckChannel    
OfflineTrans    
AutoReply   
SetScreenShotFolder 
SetEmote    
ConvertEmotes   
SetAddinUnitMemberStatus    
DeleteAddinUnitMember   
CreateAddinUnitMember   
MoveUnitMember  
DeleteUnitGroup 
MoveUnitGroup   
RenameUnitGroup 
CreateUnitGroup 
DeleteAddinUnit 
CreateAddinUnit 
GetRecentPlayerName 
GetCurrentChannelName   
ShowSomeoneMessage  
GetAppStatus    
SendEvent   
UnregisterEvent 
RegisterEvent   
SwitchChannel   
Debug   
RemoveBlackList 
AddBlackList    
SetStrangerTextColor    
SetFriendTextColor  
SetMeTextColor  
SetChannelTextColor 
SetChatFontSize 
ThrowAwayItem   
TurnTo  
MoveTo  
ShowWindow  
SizeWindow  
MoveWindow  
SetFullWindow   
Set3D   
Exit    
ExitGame    
ChangeAutoAttack    
SayEmote    
SetPhrase   
SayPhrase   
RegisterFunctionAlias   
Chat    
Say 
SwitchPrivateMsgMode    
ClearMessage    
PrintScreen 
ViewItem    
Revenge 
Trade   
InviteTeam  
JoinTeam    
CreateTeam  
MakeFriend  
ShortcutUseItem 
DirectShortcutSkill 
ShortcutSkill   
Switch  
Focus   
Replay  
Open    
RemoveCommand   
AddCommand  
Mouse_BlackList 
Mouse_ViewItem  
Mouse_Follow    
Mouse_Revenge   
Mouse_Trade 
Mouse_InviteTeam    
Mouse_JoinTeam  
Mouse_MakeFriend    
Mouse_Say   
Mouse_Emote_Menu    
Mouse_Menu  
Mouse_MoveTo    
Mouse_Force1    
Mouse_Force0    
Mouse_PartnerAction 
Mouse_Action    
showplayernumber    
showplayermana  
showplayerlife  
showplayername  
horse   
pk  
trade   
sit 
run 
ItemEx  
Tong    
ChatRoomList    
Select  
Call    
Follow  
Attack  
Talk    
Skill   
Item    
Chara   
FullScreen  
VisiblePlayer   
MissleSame  
PlayerNpc   
NewTask 
equipupgrade    
battlerank  
battlerecord    
battlestart 
battlereport    
giveitem    
DiceWeave   
portrait    
beset   
tongmanager 
tongcreate  
newsmessage 
chatroom    
normaltool  
statustool  
options 
commandline 
rightskill  
leftskill   
tasknote    
help    
friend  
system  
skills  
Items   
status  
map 
team    
pauserec    
slowdown    
speedup 
pause   
stop    
play    
endrec  
rec 
JxRep   
InfoString  
2D  
3D  
FullWindow 