QId 
Answer 
BeginSaleTime 
EndSaleTime 
BeginPayForTime 
EndPayForTime 
Price 
BonusRate 
MaxBonus  
Random 
GetCurrentDate 
GetCurrentTime 
GetSysCurrentTime 
Tm2Time 
Time2Tm 
FormatTime2Number 
FormatTime2String 
RandomSelAOnlinePlayer 
RandomSelAOnlineMap 
SaveStringToSDB 
SaveStringToSDBOw 
SaveIntegerToSDB 
SaveIntegerToSDBOw 
SaveCustomDataToSDB 
SaveCustomDataToSDBOw 
ClearRecordOnShareDB 
GetStringFromSDB 
GetIntegerFromSDB 
GetCustomDataFromSDB 
GetFirstRecordFromSDB 
NotifySDBRecordChanged 
NotifySDBRChanged1Svr 
GetRecordInfoFromNO 
GetRecordCount 
GetTaskCurCount 
IsMapOnGameSvr 
TaskLoad 
TaskRelease 
TaskName 
TaskTime 
TaskInterval 
TaskCountLimit 
OutputMsg 
Include 
IncludeLib 
IL 
GlobalExecute 
Msg2IP 
Msg2PlayerByName 
Msg2Tong 
Msg2Faction 
TaskSetMode 
TaskSetStartDay 
StartSignUp 
EndSignUp 
StartArena 
StartCityWar 
CW_GetOccupant 
CW_GetCityStatus 
CheckLotteryState 
SyncLottery 
Battle_GetRoundFlowInfo 
Battle_GetRoundInfo 
Battle_GetMapPatternInfo 
Battle_GetBattleMapInfo 
Battle_GetRuleInfo 
Battle_StartNewRound 
LoadLadder 
Ladder_ClearLadder 
Ladder_GetLadderInfo 
Ladder_NewLadder 
GetCityAreaName 
GetCityOwner 
GetTongNameByID 
SetTongMaster 
SyncAllLadder 
WriteStringToFile 
GetGblInt 
SetGblInt 
GetGblStr 
SetGblStr 
DelGblInt 
DelGblStr 
LoadScript 
GetGateWayClientID 
GetProductLanguge 
GetProductRegion 
OB_Create 
OB_Release 
OB_Copy 
OB_Append 
OB_Clear 
OB_IsEmpty 
OB_PushString 
OB_PopString 
OB_PushDouble 
OB_PopDouble 
OB_PushByte 
OB_PopByte 
OB_PushInt 
OB_PopInt 
OB_LoadShareData 
OB_SaveShareData 
OB_DeleteShareData 
DynamicExecute 
RemoteExecute 
AppointViceroy 
GetViceroy 
NW_SetTask 
NW_Abdicate 
AddStatData 
SetStatData 
AddTimer 
DelTimer 
SuspendTimer 
ResumeTimer  